package humber.android.group.six.carshare.controllers;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.Date;
import java.util.List;

import humber.android.group.six.carshare.AppDatabase;
import humber.android.group.six.carshare.R;
import humber.android.group.six.carshare.controllers.adapters.BookingHistoryAdapter;
import humber.android.group.six.carshare.daos.BookingDao;
import humber.android.group.six.carshare.daos.CarDao;
import humber.android.group.six.carshare.models.Booking;
import humber.android.group.six.carshare.models.Car;

public class BookingHistoryActivity extends AppCompatActivity {

    private SharedPreferences sharedPreferences;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_booking_history);

        RecyclerView recyclerView = findViewById(R.id.rv_booking);
        AppDatabase appDatabase = AppDatabase.getInstance(this);
        CarDao carDao = appDatabase.carDao();
        if (carDao.countCar() == 0) {
            populateCars(carDao);
        }

        BookingDao bookingDao = appDatabase.bookingDao();
        sharedPreferences = getSharedPreferences("humber.android.group.six.carshare", MODE_PRIVATE);
        List<Booking> bookings = bookingDao.getBookingsByUid(sharedPreferences.getInt("uid", -1));

        BookingHistoryAdapter bookingHistoryAdapter = new BookingHistoryAdapter(bookings, carDao, this);

        recyclerView.setAdapter(bookingHistoryAdapter);

        recyclerView.setLayoutManager(new LinearLayoutManager(this));
    }

    private void populateCars(CarDao carDao) {
        carDao.insertCar(new Car("Honda", "Pilot", "635 Westburne Dr, Concord, ON L4K 4T6", 3, new Date(), 133.3, 4.5, "The Honda Pilot is a mid-size crossover SUV with three-row seating manufactured by Honda since 2002. Primarily aimed at the North American market, the Pilot is the largest SUV produced by Honda. Pilots are currently manufactured in Lincoln, Alabama, and the Pilot was produced in Alliston, Ontario until April 2007. The first generation Pilot was released in April 2002 as a 2003 model.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/03-2021-honda-pilot-elite-source-1611126742.jpg?crop=0.9995454545454546xw:1xh;center,top&resize=980:*", true));
        carDao.insertCar(new Car("Toyota", "4Runner", "8074 Islington Ave, Woodbridge, ON L4L 1W5", 3, new Date(), 123.4, 4.5, "The Toyota 4Runner is an SUV manufactured by the Japanese automaker Toyota and marketed globally since 1984, across five generations. In Japan, it was marketed as the Toyota Hilux Surf (Japanese: トヨタ・ハイラックスサーフ, Hepburn: Toyota Hairakkususāfu) and was withdrawn from the market in 2009. The original 4Runner was a compact SUV and little more than a Toyota Hilux pickup truck with a fiberglass shell over the bed, but the model has since undergone significant independent development into a cross between a compact and a mid-size SUV. All 4Runners have been built in Japan at Toyota's plant in Tahara, Aichi, or at the Hino Motors (a Toyota subsidiary) plant in Hamura.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2022-toyota-4runner-trd-sport-102-1622508059.jpg?crop=0.400xw:0.344xh;0.314xw,0.373xh&resize=980:*", true));
        carDao.insertCar(new Car("Ford", "Escape", "797 College St, Toronto, ON M6G 1C7", 3, new Date(), 333.3, 4.5, "The Ford Escape is a compact crossover SUV sold by Ford since 2000 over four generations. The first generation was jointly developed with Mazda which also created the Mazda Tribute and Mercury Mariner as the twin model. Second generations of the Ford Escape, Mercury Mariner, and Mazda Tribute were released in 2007 for the 2008 model year, but mostly restricted to North America. In other markets, the first generation models were either replaced by updated first generation versions, or replaced by the Mazda CX-7 (2006) and Ford Kuga (2008). Unlike the collaborative approach taken with the previous model, this time the design and engineering was carried out solely by Ford. Since 2013, the model has been paralleled with the Kuga sold outside North America, making them essentially identical. A hybrid option was again available.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-ford-escape-se-1591808298.jpg?crop=0.685xw:0.685xh;0.306xw,0.315xh&resize=980:*", true));
        carDao.insertCar(new Car("Hyundai", "Tucson", "1952 Gerrard St E, Toronto, ON M4E 2B1", 3, new Date(), 432.1, 4.5, "The Hyundai Tucson (Korean: 현대 투싼) (pronounced Tu-són) is a compact crossover SUV (C-segment) produced by the South Korean manufacturer Hyundai since 2004. In the brand's lineup, the Tucson is positioned below the Santa Fe, and above the Kona and Creta. It is named after the city of Tucson, Arizona. The second-generation model has been marketed as the Hyundai ix35 in several markets, including Europe, Australia and China, before reverting to Tucson for the third-generation.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-hyundai-tucson-25-limited-awd-114-1623351417.jpg?crop=0.871xw:0.797xh;0.0890xw,0.0984xh&resize=980:*", true));
        carDao.insertCar(new Car("Subaru", "Outback", "7 Curity Ave, Toronto, ON M4B 3L8", 3, new Date(), 987.7, 4.5, "The Subaru Outback is an automotive nameplate used by the Japanese automaker Subaru for two different vehicles: a crossover station wagon, the Outback (1994–present, also sold as Legacy Outback (Japanese: スバル・レガシィアウトバック, Hepburn: Subaru Regashi Autobakku) in some markets), and an Impreza-derived hatchback, the Outback Sport (1994–2011).", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-subaru-outback-touring-2p5l-102-1578936313.jpg?crop=0.740xw:0.741xh;0.260xw,0.184xh&resize=980:*", true));
        carDao.insertCar(new Car("Subaru", "Forester", "625 Pharmacy Ave, Scarborough, ON M1L 3H3", 3, new Date(), 765.3, 4.5, "The Subaru Forester (Japanese: スバル・フォレスター, Hepburn: Subaru Foresutā) is a compact crossover SUV that has been manufactured by Subaru since 1997. The first generation was built on the platform of the Impreza in the style of a taller station wagon, a style that continued to the second generation, while the third-generation model onwards moved towards a crossover SUV design. A performance model was available for the second-generation Forester in Japan as the Forester STi.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-subaru-forester-mmp-1-1556732408.jpg?crop=0.701xw:0.702xh;0.262xw,0.187xh&resize=980:*", true));
        carDao.insertCar(new Car("Chevrolet", "Equinox", "55 Lebovic Ave #110, Scarborough, ON M1L 4V9", 3, new Date(), 754.3, 4.5, "The Chevrolet Equinox is a series of crossover SUVs from Chevrolet introduced in 2004 for the 2005 model year. It replaces the North American Chevrolet Tracker and Chevrolet S-10 Blazer. The third-generation Equinox also replaced the first-generation Chevrolet Captiva.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-chevrolet-equinox-premier-020-1-1580959033.jpg?crop=0.804xw:0.835xh;0.0323xw,0.130xh&resize=980:*", true));
        carDao.insertCar(new Car("Mazda", "CX-5", "34 Stratton Ave, Scarborough, ON M1K 3V4", 3, new Date(), 678.3, 4.5, "The Mazda CX-5 is a compact crossover SUV produced by Mazda since 2012. A successor to both the Tribute and the slightly larger CX-7, it is Mazda's first model to feature the 'Kodo' design language and the first model to be fully developed with a range of technologies branded as Skyactiv, including a rigid, lightweight platform combined with a series of engines and transmissions to reduce emissions and fuel consumption.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-mazda-cx-5-signature-40k-111-1604004852.jpg?crop=0.886xw:0.811xh;0.114xw,0.158xh&resize=980:*", true));
        carDao.insertCar(new Car("Tesla", "Model Y", "2141 Kipling Ave, Etobicoke, ON M9W 4K8", 3, new Date(), 435.4, 4.5, "The Tesla Model Y is a battery electric compact crossover manufactured by Tesla, Inc. Unveiled in March 2019, it started production at its Fremont plant in January 2020, and started deliveries on March 13, 2020.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-tesla-model-y-performance-109-1625065341.jpg?crop=0.741xw:0.679xh;0.177xw,0.219xh&resize=980:*", true));
        carDao.insertCar(new Car("Honda", "Accord", "131 Royal Group Crescent, Woodbridge, ON L4H 1X9", 3, new Date(), 546.8, 4.5, "The Honda Accord (Japanese: ホンダ・アコード, Hepburn: Honda Akōdo, /əˈkɔːrd/), also known as the Honda Inspire (Japanese: ホンダ・インスパイア, Hepburn: Honda Insupaia) in Japan and China for certain generations, is a series of cars manufactured by Honda since 1976, best known for its four-door sedan variant, which has been one of the best-selling cars in the United States since 1989. The Accord nameplate has been applied to a variety of vehicles worldwide, including coupes, station wagons, hatchbacks and a Honda Crosstour crossover.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-honda-accord-hybrid-109-edit-1604961241.jpg?crop=0.682xw:0.625xh;0.0561xw,0.375xh&resize=980:*", true));
        carDao.insertCar(new Car("Jeep", "Wrangler", "58 Seascape Crescent, Brampton, ON L6P 3C5", 3, new Date(), 786.3, 4.5, "The Jeep Wrangler is a series of compact and mid-size four-wheel drive off-road SUVs manufactured by Jeep since 1986, and currently in its fourth generation. The Wrangler JL, the most recent generation, was unveiled in late 2017 and is produced at Jeep's Toledo Complex.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-jeep-wrangler-rubicon-392-107-1605547524.jpg?crop=1.00xw:0.918xh;0,0.0434xh&resize=980:*", true));
        carDao.insertCar(new Car("Ford", "Explorer", "30 Lethbridge Dr, Brampton, ON L6S", 3, new Date(), 675.2, 4.5, "The Ford Explorer is a range of SUVs manufactured by Ford Motor Company since the 1991 model year. The first four-door SUV produced by Ford, the Explorer was introduced as a replacement for the two-door Bronco II. Within the current Ford light truck range, the Explorer is slotted between the Ford Edge and Ford Expedition. As with the Ford Ranger, the Explorer derives its name from a trim package previously offered on the Ford F-Series pickup trucks.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2022-ford-explorer-107-1614108646.jpg?crop=0.597xw:0.534xh;0.196xw,0.424xh&resize=980:*", true));
        carDao.insertCar(new Car("GMC", "Sierra", "44 Wild Indigo Crescent, Brampton, ON L6R 2J9", 3, new Date(), 234.3, 4.5, "The Chevrolet Suburban is a series of automobiles built by the Chevrolet division of General Motors. The name started in 1934 for the 1935 U.S. model year, making it the longest continuously used automobile nameplate in production. It has traditionally been one of General Motors' most profitable vehicles. The 1935 first generation Carryall Suburban was one of the first production all-metal bodied station wagons. It now has a full-size SUV body style and comes with three engine options: a 5.3 liter V8, 6.2 liter V8 or a 3.0 liter Inline-6 turbo diesel.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-gmc-sierra-hd-denali-119-1600970632.jpg?crop=1xw:0.9171252292813072xh;center,top&resize=980:*", true));
        carDao.insertCar(new Car("Toyota", "Corolla", "99 Bonnieglen Farm Blvd, Caledon, ON L7C 4B7", 3, new Date(), 788.3, 4.5, "The Toyota Corolla (Japanese: トヨタ・カローラ, Hepburn: Toyota Karōra) is a series of compact cars (formerly subcompact) manufactured and marketed globally by the Toyota Motor Corporation. Introduced in 1966, the Corolla was the best-selling car worldwide by 1974 and has been one of the best-selling cars in the world since then. In 1997, the Corolla became the best-selling nameplate in the world, surpassing the Volkswagen Beetle. Toyota reached the milestone of 50 million Corollas sold over twelve generations in 2021.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-toyota-corolla-105-1557931648.jpg?crop=1xw:0.9997727789138833xh;center,top&resize=980:*", true));
        carDao.insertCar(new Car("Toyota", "Camry", "1195 Meyerside Dr, Mississauga, ON L5T 1E5", 3, new Date(), 234.6, 4.5, "The Toyota Camry (/ˈkæmri/; Japanese: トヨタ・カムリ Toyota Kamuri) is an automobile sold internationally by the Japanese auto manufacturer Toyota since 1982, spanning multiple generations. Originally compact in size (narrow-body), the Camry has grown since the 1990s to fit the mid-size classification (wide-body)—although the two widths co-existed in that decade. Since the release of the wide-bodied versions, Camry has been extolled by Toyota as the firm's second 'world car' after the Corolla. As of 2022, the Camry is positioned above the Corolla and below the Avalon or Crown in several markets.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-toyota-camry-xle-awd-106-1611955351.jpg?crop=0.808xw:0.740xh;0.117xw,0.122xh&resize=980:*", true));
        carDao.insertCar(new Car("Toyota", "Tacoma", "2561 Stanfield Rd, Mississauga, ON L4Y 1R6", 3, new Date(), 243.4, 4.5, "The Toyota Tacoma is a pickup truck manufactured by the Japanese automobile manufacturer Toyota since 1995. The first-generation Tacoma (model years 1995 through 2004) was classified as a compact pickup. The second generation (model years 2005 through 2015) as well as the third generation (in production since 2015) are classified as mid-sized pickups. The Tacoma was Motor Trend's Truck of the Year for 2005.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-toyota-tacoma-2-1591806914.jpg?crop=1.00xw:0.918xh;0,0.0510xh&resize=980:*", true));
        carDao.insertCar(new Car("Honda", "Civic", "45 Ripley Ave, Toronto, ON M6S 3P2", 3, new Date(), 133.3, 345.43, "The Honda Civic (Japanese: ホンダ・シビック, Hepburn: Honda Shibikku) is a series of automobiles manufactured by Honda since 1972. Since 2000, the Civic has been categorized as a compact car, while previously it occupied the subcompact class. As of 2021, the Civic is positioned between the Honda Fit/City and Honda Accord in Honda's global car line-up.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2022-honda-civic-sedan-111-1623810391.jpg?crop=0.801xw:0.733xh;0.0572xw,0.181xh&resize=980:*", true));
        carDao.insertCar(new Car("Toyota", "Highlander", "2067 Dundas St W, Toronto, ON M6R 1W8", 3, new Date(), 542.2, 4.5, "The Toyota Highlander, also known as the Toyota Kluger (Japanese: トヨタ・クルーガー, Hepburn: Toyota Kurūgā), is a mid-size crossover SUV with three-row seating produced by Toyota since 2000.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-toyota-highlander-hybrid-platintested87-1612898812.jpg?crop=0.901xw:0.903xh;0.0340xw,0.0446xh&resize=980:*", true));
        carDao.insertCar(new Car("Jeep", "Grand Cherokee", "243 Seaton St, Toronto, ON M5A 2T5", 3, new Date(), 324.4, 4.5, "The Jeep Grand Cherokee is a range of mid-size SUVs produced by the American manufacturer Jeep. At its introduction, while most SUVs were still manufactured with body-on-frame construction, the Grand Cherokee has used a unibody chassis from the start.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-jeep-grand-cherokee-l-104-1623870023.jpg?crop=0.784xw:0.731xh;0.0935xw,0.176xh&resize=980:*", true));
        carDao.insertCar(new Car("Nissan", "Rogue", "153 Winchester St, Toronto, ON M4X 1B5", 3, new Date(), 234.3, 4.5, "The Nissan Rogue is a compact crossover SUV produced by the Japanese automobile manufacturer Nissan. It made its debut in October 2007 for the 2008 model year. Beginning in 2013 for the 2014 model year, the model has been paralleled with the X-Trail sold outside the United States and Canada, making them identical. It is currently Nissan's best-selling vehicle in the United States.", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-nissan-rogue-1-1610479104.jpg?crop=0.726xw:0.666xh;0.274xw,0.296xh&resize=980:*", true));
    }

    public void addBooking(View view) {
        this.startActivity(new Intent(this, SearchActivity.class));
    }

    public void logout(View view) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.clear();
        editor.apply();
        this.startActivity(new Intent(this, MainActivity.class));
        this.finish();
    }
}